### ISSUE TITLE
Rasmlar maketdan noto'g'ri olingan

### ISSUE THREAD

**Issue by Javohirshakh** [IlhomYuldoshev/AnsorMed-repo#2]
Rasmlar maketdan olinganda rasmning o'zi emas, orqasidan rang bilan birgalikda olingan.

![image](https://user-images.githubusercontent.com/77332200/133572410-96ddd03d-a4fd-49fe-b636-8c2a261d1f4e.png)

**Comment by IlhomYuldoshev** [comment]
png da olish kk demoqcimisiz
lekin jpgda joyi kichkina ekan wunga jpgda olingan
![image](https://user-images.githubusercontent.com/89073838/133887403-8aa03960-4aa0-49b1-8dac-b08b18aa2cfc.png)
