### ISSUE TITLE
Logotip linki 

### ISSUE THREAD

**Issue by Javohirshakh** [IlhomYuldoshev/AnsorMed-repo#3]
Logotip agar rasm va sayt nomi html element sifatida qo'yilishi kerak bo'lsa, rasm va span bitta a (link) ichiga olinadi. Sizda esa bu ikkalasiga alohida alohida a teglari berilgan 
![image](https://user-images.githubusercontent.com/77332200/133572959-8fd17ec4-87c1-4f65-8889-f7fa1d0a9e3f.png)

**Comment by IlhomYuldoshev** [comment]
to'g'irlandi
